Test Agent

diff --git a/src/agentTest/download-secure-file-steps-lin.yml b/src/agentTest/download-secure-file-steps-lin.yml
--- a/src/agentTest/download-secure-file-steps-lin.yml
+++ b/src/agentTest/download-secure-file-steps-lin.yml
@@ -7,10 +7,9 @@ steps:
 
 - bash: |
     if [ -f $(secureFile.secureFilePath)] then
-        echo "$(secureFile.secureFilePath) exists"
+        echo "$(secureFile.secureFilePath) exists";
     else
-        echo "Not found: $(secureFile.secureFilePath)"
-        ls $(secureFile.secureFilePath)
-        exit 1
+        echo "Not found: $(secureFile.secureFilePath)";
+        exit 1;
     fi
   displayName: Check if secure file exists
diff --git a/templates/test-install-key-lin.yml b/templates/test-install-key-lin.yml
--- a/templates/test-install-key-lin.yml
+++ b/templates/test-install-key-lin.yml
@@ -18,9 +18,9 @@ steps:
   displayName: Clone Sample Repo
 - bash: |
     if [ -d azure-samples then
-        echo "azure-samples exists"
+        echo "azure-samples exists";
     else
-        echo "Not found: azure-samples"
-        exit 1
+        echo "Not found: azure-samples";
+        exit 1;
     fi
   displayName: Check if git cloned
